apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontier-llama
  namespace: default
  labels:
    app: frontier-llama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontier-llama
  template:
    metadata:
      labels:
        app: frontier-llama
    spec:
      containers:
        - name: frontier-llama
          image: ""
          ports:
            - containerPort: 8097
          resources:
            limits:
              memory: "2Gi" 
              cpu: "200m"
            requests:
              memory: "1Gi"
              cpu: "100m"
          
