apiVersion: v1
kind: Service
metadata:
  name: frontier-llama
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8097
    protocol: TCP
  selector:
    app: frontier-llama
  type: LoadBalancer