# apiVersion: v1
# kind: Service
# metadata:
#   name: frontier-bot
#   namespace: default
# spec:
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080
#     protocol: TCP
#   selector:
#     app: frontier-bot
#   type: LoadBalancer