apiVersion: v1
kind: Service
metadata:
  name: frontier-bot
  namespace: default
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: frontier-bot
  type: LoadBalancer